addons:
  apt:
    packages:
      - libgconf-2-4
matrix:
  include:
    - language: node_js
      before_install: cd front-end
      script: npm run validate

    - language: ruby
      before_install: cd auth
      script: bundle exec rspec

cache:
  directories:
    - ~/.cache
