sudo: false
addons:
  apt:
    packages:
      - libgconf-2-4
matrix:
  include:
    - language: node_js
      before_install:
        - cd front-end
      install:
        - yarn install --frozen-lockfile --silent

    - language: ruby
      before_install:
        - cd auth
      script: rspec

notifications:
  email:
    - aecovarru@gmail.com
cache:
  directories:
    - ~/.npm
    - ~/.cache
