version: "3.7"

services:
  client-test:
    build:
      context: .
      dockerfile: ./client/Dockerfile.test
    command: bash -c 'yarn test:inband'
    volumes:
      - .:/app
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  server-test:
    build:
      context: .
      dockerfile: ./server/Dockerfile.test
    command: bash -c 'rake db:build && rake test:run'
    volumes:
      - ./server:/server
    depends_on:
      - db
  cypress:
    command: ./node_modules/.bin/cypress run
    build:
      context: .
      dockerfile: ./e2e/Dockerfile.cypress
    volumes:
      - ./e2e/:/e2e
