version: "3.7"

services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
