FROM node:14.4.0

# set working directory
WORKDIR /app/client

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/client/node_modules/.bin:$PATH

# install app dependencies
COPY ./client/package.json ./
COPY ./client/yarn.lock ./
RUN yarn --silent

# add app
COPY ./client/ ./
