version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rake db:setup && rake server:start"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
