- hosts: localhost
  gather_facts: False

  tasks:
    - name: Create admin user to follow user best practices
      iam:
        iam_type: user
        name: "{{ lookup('env','USERNAME') }}"
        state: present
        password: "{{ lookup('env','PASSWORD') }}"
        access_key_state: create

    - iam_group:
        name: admin
        managed_policy:
          - arn:aws:iam::aws:policy/AdministratorAccess
        users:
          - "{{ lookup('env','USERNAME') }}"
        state: present
